import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import{Inter} from "next/font/google"
import Providers from "@/components/providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Google Fonts Inter
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["600", "700"],
});

export const metadata: Metadata = {
  title: "Exam App",
  description: "Generated by Ahmed Hosin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}>
        <Providers>
            {children}
        </Providers>
      </body>
    </html>
  );
}
